### PR TITLE
remove dependency on edx rest api client

### PR DESCRIPTION
**Pull request by matthugs**

### CODE REVIEW

**Review by alangsto — COMMENTED** [review]
This looks good to me, but why are we removing rest_api_client as a dependency?

**Comment by matthugs** [comment]
@alangsto the edx-rest-api-client package is meant to be used for Django-based clients, one of which the mockprock is not. Newer versions of the client library add a dependency on django caching features, which causes a stack trace like
```Traceback (most recent call last):
  File "/Users/mhughes/workspace/src/mockprock/mockprock/server.py", line 223, in make_ready_callback
    response = app.client.post(callback_url, json=payload).json()
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_rest_api_client/client.py", line 282, in request
    self._ensure_authentication()
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_rest_api_client/client.py", line 249, in _ensure_authentication
    oauth_access_token_response = get_and_cache_oauth_access_token(
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_rest_api_client/client.py", line 153, in get_and_cache_oauth_access_token
    cached_response = TieredCache.get_cached_response(cache_key)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_django_utils/cache/utils.py", line 191, in get_cached_response
    django_cached_response = cls._get_cached_response_from_django_cache(key)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_django_utils/cache/utils.py", line 261, in _get_cached_response_from_django_cache
    cached_value = django_cache.get(key, _CACHE_MISS)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/core/cache/__init__.py", line 74, in __getitem__
    if alias not in settings.CACHES:
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by matthugs** [comment]
@alangsto the edx-rest-api-client package is meant to be used for Django-based clients, one of which the mockprock is not. Newer versions of the client library add a dependency on django caching features, which causes a stack trace like
```Traceback (most recent call last):
  File "/Users/mhughes/workspace/src/mockprock/mockprock/server.py", line 223, in make_ready_callback
    response = app.client.post(callback_url, json=payload).json()
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_rest_api_client/client.py", line 282, in request
    self._ensure_authentication()
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_rest_api_client/client.py", line 249, in _ensure_authentication
    oauth_access_token_response = get_and_cache_oauth_access_token(
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_rest_api_client/client.py", line 153, in get_and_cache_oauth_access_token
    cached_response = TieredCache.get_cached_response(cache_key)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_django_utils/cache/utils.py", line 191, in get_cached_response
    django_cached_response = cls._get_cached_response_from_django_cache(key)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/edx_django_utils/cache/utils.py", line 261, in _get_cached_response_from_django_cache
    cached_value = django_cache.get(key, _CACHE_MISS)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/core/cache/__init__.py", line 74, in __getitem__
    if alias not in settings.CACHES:
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/mhughes/.virtualenvs/mockprock/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by alangsto** [comment]
@matthugs that makes sense, would you mind adding a short comment in the auth.py or client.py to explain that? Thank you!

**Review by alangsto — APPROVED** [review]

**Pull request merged**
